[notice]
title = "V MOVIE ─ Notice"
url = "https://www.vlive.tv/channel/FA1A3/board/171"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li"
titleSelector = "//a/div/div[1]/div[1]/strong"
linkSelector = "//a[@class='post_area--1y4Lh']"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dateSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[media]
title = "V MOVIE ─ Media Board"
url = "https://www.vlive.tv/channel/FA1A3/board/3641"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li[contains(@class,'post_item')]"
titleSelector = "//a/div/div[1]/div/strong"
linkSelector = "//a[@class='post_area--3dKbo']"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dateSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"
